name: Linting and Type checking

on: pull_request

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3

  ruff-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff
